version: "3"
services:
  mongo:
    container_name: mongo-doenet
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    networks:
      - default
    volumes:
      - ./server/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./server/docker-setup/mongo/mongo-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mern_docker_starter
      - MONGO_INITDB_USER=local_user
      - MONGO_INITDB_PASSWORD=Password123

  backend:
    container_name: node-doenet
    build:
      context: ./server
      dockerfile: docker-setup/node/development/Dockerfile
    networks:
      - default
      - frontend
    volumes:
      - ./server:/home/node/app
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env.development
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    container_name: react-doenet
    build:
      context: ./client
      dockerfile: docker-setup/react/development/Dockerfile
    networks:
      - frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/frontend
    depends_on:
      - backend
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"

networks:
  default:
    name: backend-network-doenet
  frontend:
    name: frontend-network-doenet
